### ISSUE TITLE
Missing vignette

### ISSUE THREAD

**Issue by kvittingseerup** [markrobinsonuzh/DRIMSeq#1]
I'm very curious to take a closer look at the transcript level analysis and would therefore like to take a closer look at the vignette. Using the 

   browseVignettes("DRIMSeq")

I get the error:

   No vignettes found by browseVignettes("DRIMSeq")

When I look it does not appear to be a knitted version of the vignette distributed with the package...?

**Comment by markrobinsonuzh** [comment]
You could try the one built by BioC:
http://bioconductor.org/packages/release/bioc/vignettes/DRIMSeq/inst/doc/DRIMSeq.pdf
